/*
 * This program will assign a random number to the variable "n" each time it is executed  
 * 
 * This program will assign a random number to the variable "n" each time it is executed.  
 *
 *It will print whether the number stored in the variable n is positive or negative.                                               
 *                                                                                                                                
 */

#include <stdlib.h>                   
#include <time.h>                                                                                                                  
#include <stdio.h>

int main(void)
{
	int n;
	srand(time(0));
	 n = rand() - RAND_MAX / 2; /*rand() is used to generate a series of random numbers. The random number is generated by using
				      an algorithm that gives a series of non-related numbers whenever this function is called */ 

	 /*The below if statement checks for a positve number "n" above zero and prints it*/ 
	if(n > 0) 
	{
		printf("%d is positive\n", n);  

	}

	/*The below else if statement checks for negaive number "n" below zero and prints it*/  
	else if(n < 0) 
	{
		printf("%d is negative\n", n);  

	}

	/*Then the below else statement for for zero number "n" and prints it is all the above statement did work*/ 
	else
	{
		printf("%d is zero\n", n); 
	}
	
	return (0);
}
